### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by aberthil** [calvarium/homebridge-lifx-plugin#36]
Plugin not working

**Logs:**

LIFX Client invalid packet header error
Packet:  240080350000000000000000
Trace: RangeError: The value of "offset" is out of range. It must be >= 0 and <= 11. Received 22
    at new NodeError (node:internal/errors:406:5)
    at boundsError (node:internal/buffer:88:9)
    at Uint8Array.readUInt8 (node:internal/buffer:254:5)
    at Object.Packet.headerToObject (/usr/local/lib/node_modules/homebridge-lifx-plugin/node_modules/lifx-lan-client/src/lifx/packet.js:131:39)
    at Object.Packet.toObject (/usr/local/lib/node_modules/homebridge-lifx-plugin/node_modules/lifx-lan-client/src/lifx/packet.js:162:16)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-plugin/node_modules/lifx-lan-client/src/lifx/client.js:205:30)
    at Socket.emit (node:events:514:28)
    at UDP.onMessage (node:dgram:941:8) {
  code: 'ERR_OUT_OF_RANGE'
}
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-plugin/node_modules/lifx-lan-client/src/lifx/client.js:211:15)
    at Socket.emit (node:events:514:28)
    at UDP.onMessage (node:dgram:941:8)

**Plugin Config:**

        {
            "name": "Lifx Plugin",
            "duration": 0,
            "brightnessDuration": 300,
            "colorDuration": 300,
            "default": "0.0.0.0",
            "broadcast": "255.255.255.255",
            "lightOfflineTolerance": 3,
            "messageHandlerTimeout": 45000,
            "resendPacketDelay": 150,
            "resendMaxTimes": 3,
            "updates": true,
            "debug": false,
            "autoDiscover": true,
            "platform": "LifxPlugin"
        }

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**:   1.7.0
* **Node.js Version**:   20.9.0
* **NPM Version**:  10.1.0
* **Operating System**:  macOS

**Comment by calvarium** [comment]
So, when does the error occur?

**Comment by aberthil** [comment]
When the plug in is trying to load On Nov 8, 2023, at 11:35 AM, calvarium ***@***.***> wrote:﻿
So, when does the error occur?

**Comment by aberthil** [comment]
I played a bit with it, removed it and installed again, it always crashed.
Now if I remove the auto discovery it does not crash and if I add the lights one by one by IP address it seems to work fine.
Seem like a nice bug here :-)
Alexis

**Comment by calvarium** [comment]
It seems to me that one of your devices is behaving strangely. Did you manage to add each device by its IP?

If you could provide a full log from the start of the plugin to the occurrence of this error message, that would be helpful.
If you enable debug in your homebridge, the log will be even more detailed.

**Comment by aberthil** [comment]
Will have a look, might be one that has issues indeed will reset it to default and reinstall to check if this is it

**Comment by malwcal** [comment]
HI,  my devices started doing this as well.  See the error below.  This happens again and again every few seconds.  I am not sure which device is causing this.  I have not done anything to cause this (as far as I know!), it just started happening.

`LIFX Client invalid packet header error
Packet:  240080350000000000000000
Trace: RangeError: The value of "offset" is out of range. It must be >= 0 and <= 11. Received 22
    at new NodeError (node:internal/errors:406:5)
    at boundsError (node:internal/buffer:88:9)
    at Uint8Array.readUInt8 (node:internal/buffer:254:5)
    at Object.Packet.headerToObject (/usr/lib/node_modules/homebridge-lifx-plugin/node_modules/lifx-lan-client/src/lifx/packet.js:131:39)
    at Object.Packet.toObject (/usr/lib/node_modules/homebridge-lifx-plugin/node_modules/lifx-lan-client/src/lifx/packet.js:162:16)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-lifx-plugin/node_modules/lifx-lan-client/src/lifx/client.js:205:30)
    at Socket.emit (node:events:514:28)
    at UDP.onMessage (node:dgram:941:8) {
  code: 'ERR_OUT_OF_RANGE'
}
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-lifx-plugin/node_modules/lifx-lan-client/src/lifx/client.js:211:15)
    at Socket.emit (node:events:514:28)
    at UDP.onMessage (node:dgram:941:8)
`
