### ISSUE TITLE
Adding a specific Z strip causes a null pointer error that crashes the plugin

### ISSUE THREAD

**Issue by huw** [calvarium/homebridge-lifx-plugin#7]
**Describe The Bug:**
When running the plugin in auto-discovery mode, I get a null pointer error that causes Homebridge to `SIGTERM` and restart. I isolated the issue to a specific Z strip (I have 3), and I’m not sure why—but the stacktrace leads me to believe it’s probably not loading the device config properly. It seems to load the strip into `cachedAccessories`, so it’s able to discover it fine, just not load it.

**To Reproduce:**
Run the plugin with auto-discovery set to `true`, without `exclude`ing the specific Z strip in question.

**Expected behavior:**
I expect the plugin the load the Z strip correctly.

**Logs:**

```
[1/22/2022, 10:54:40 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[1/22/2022, 10:54:41 PM] [HB Supervisor] Started Homebridge v1.4.0 with PID: 1622
[1/22/2022, 10:54:49 PM] Loaded config.json with 0 accessories and 3 platforms.
[1/22/2022, 10:54:50 PM] Loaded 17 cached accessories from cachedAccessories.
[1/22/2022, 10:54:50 PM] ---
[1/22/2022, 10:54:59 PM] Loaded plugin: homebridge-config-ui-x@4.42.0
[1/22/2022, 10:54:59 PM] Registering platform 'homebridge-config-ui-x.config'
[1/22/2022, 10:54:59 PM] ---
[1/22/2022, 10:55:03 PM] Loaded plugin: homebridge-dyson-pure-cool@2.1.0
[1/22/2022, 10:55:03 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
[1/22/2022, 10:55:03 PM] ---
[1/22/2022, 10:55:04 PM] Loaded plugin: homebridge-lifx-plugin@0.1.20
[1/22/2022, 10:55:04 PM] Registering platform 'homebridge-lifx-plugin.LifxPlugin'
[1/22/2022, 10:55:04 PM] ---
[1/22/2022, 10:55:04 PM] Loading 3 platforms...
[1/22/2022, 10:55:04 PM] [Config] Initializing config platform...
[1/22/2022, 10:55:04 PM] [Config] Running in Service Mode
[1/22/2022, 10:55:04 PM] [DysonPureCoolPlatform] Initializing DysonPureCoolPlatform platform...
[1/22/2022, 10:55:04 PM] [LIFX Plugin] Initializing LifxPlugin platform...
[1/22/2022, 10:55:05 PM] [DysonPureCoolPlatform] Accessories initialized.
Setup Payload:
X-HM://XXXXXXXXXXXXXX
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXX-XX-XXX │     
    └────────────┘     
                       
[1/22/2022, 10:55:06 PM] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge EAE7) is running on port XXXXX.
[1/22/2022, 10:55:09 PM] [homebridge-lifx-plugin] This plugin generated a warning from the characteristic 'Manufacturer': characteristic value expected string and received undefined. See https://git.io/JtMGR for more info.
[1/22/2022, 10:55:09 PM] [homebridge-lifx-plugin] This plugin generated a warning from the characteristic 'Model': characteristic value expected string and received undefined. See https://git.io/JtMGR for more info.
[1/22/2022, 10:55:10 PM] TypeError: Cannot read properties of undefined (reading 'color')
    at Bulb.hasColors (/usr/local/lib/node_modules/homebridge-lifx-plugin/src/bulb.ts:62:46)
    at LifxPlatformAccessory.bindFunctions (/usr/local/lib/node_modules/homebridge-lifx-plugin/src/platformAccessory.ts:57:19)
    at /usr/local/lib/node_modules/homebridge-lifx-plugin/src/platformAccessory.ts:27:12
    at /usr/local/lib/node_modules/homebridge-lifx-plugin/src/bulb.ts:33:9
    at /usr/local/lib/node_modules/homebridge-lifx-plugin/src/bulb.ts:79:7
    at /usr/local/lib/node_modules/homebridge-lifx-plugin/src/bulb.ts:112:7
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-plugin/node_modules/lifx-lan-client/lib/lifx/light.js:236:5)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-plugin/node_modules/lifx-lan-client/lib/lifx/client.js:451:26)
    at Array.forEach (<anonymous>)
    at Client.processMessageHandlers (/usr/local/lib/node_modules/homebridge-lifx-plugin/node_modules/lifx-lan-client/lib/lifx/client.js:438:24)
[1/22/2022, 10:55:10 PM] Got SIGTERM, shutting down Homebridge...
```

It seems as if it is incorrectly loading an accessory’s config as `null`, which causes the other two warnings about missing `Manufacturer` and `Model`.

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge EAE7",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 0,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 80,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "devices": [
                {
                    "ipAddress": "XXXXXX",
                    "serialNumber": "XXXXXX",
                    "credentials": "XXXXXX",
                    "enableAutoModeWhenActivating": true,
                    "enableOscillationWhenActivating": true,
                    "isNightModeEnabled": false,
                    "isJetFocusEnabled": false,
                    "isContinuousMonitoringEnabled": false,
                    "isTemperatureSensorEnabled": false,
                    "isHumiditySensorEnabled": true,
                    "isAirQualitySensorEnabled": true,
                    "isSingleSensorAccessoryModeEnabled": false,
                    "isSingleAccessoryModeEnabled": true,
                    "isFullRangeHumidity": false,
                    "isHeatingDisabled": false
                }
            ],
            "platform": "DysonPureCoolPlatform"
        },
        {
            "name": "LIFX Plugin",
            "duration": 300,
            "brightnessDuration": 300,
            "colorDuration": 300,
            "default": "0.0.0.0",
            "broadcast": "255.255.255.255",
            "lightOfflineTolerance": 3,
            "messageHandlerTimeout": 45000,
            "resendPacketDelay": 150,
            "resendMaxTimes": 3,
            "debug": false,
            "autoDiscover": true,
            "platform": "LifxPlugin",
            "exclude": [
              {}
            ]
        }
    ]
}
```

**Environment:**

* **Plugin Version**: v0.1.20
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.3.2
* **NPM Version**: 8.3.2
* **Operating System**: Raspbian running on Raspberry Pi Zero W 1.1
* **LIFX Version**: 4.11.0 (2/ff85dc8) (v2.80) (v3.70-BULB)
* **LIFX Lights**:
  * 10x Downlight (Latest Gen—I think that’s Gen 3?)
  * 3x A19 (1x Gen 4, 2x Gen 3)
  * 1x Mini Colour (Gen 3)
  * 3x Z Strip (2x 1500K, 1x 2500K)—1 of the 1500Ks isn’t working, but the other is. The 2500K works.

**Comment by huw** [comment]
Updated the issue because I was able to isolate it to a specific Z strip. This isn’t urgent; I hardly use this one and am fine with having it run over normal HomeKit.

**Comment by calvarium** [comment]
Hi huw,
I've racked my brain now, but unfortunately can't reproduce your error.
You can try to activate the debug mode of my plugin or start the homebridge in debug mode (homebridge -D).
Does the strip have the latest firmware or could a bad connection cause the problem?
Let me know if you find out something new

**Comment by huw** [comment]
Nah, it’s fine in the app & has the latest firmware. I’ll update the issue if I get around to enabling the debug flags on Homebridge (the plugin’s debug mode didn’t show anything enlightening other than what looked like readouts of the Bonjour packets); I suspect this is something that will need a step-through debugger to figure out.

I was thinking of maybe contributing to the plugin, so if I do I might try and debug this at the same time. Will just depend on how much time I have.

Cheers for the good work—this has been a _life-saver_ over their official HomeKit support and I’m so glad I found it.

**Comment by calvarium** [comment]
I'm proud of you for saying that and glad it saved you time.
Feel free to troubleshoot the plugin and let me know if you figure anything out.
